FROM python:3.11-slim-buster

WORKDIR /root
ENV PYTHONPATH /root

RUN apt-get update && apt-get install -y build-essential git

RUN pip install prometheus_client grpcio-health-checking
RUN pip install flyteidl==1.11.0b0 \
    git+https://github.com/flyteorg/flytekit.git@master \
    git+https://github.com/flyteorg/flytekit.git@284436347d21af3a1eee86434c18ccd0b8072835#subdirectory=plugins/flytekit-awssagemaker-inference

CMD pyflyte serve agent --port 8000
